#!/usr/bin/env bash
# ==============================================================================
# 02_postgresql_conf_changes.sh — Harden postgresql.conf on Server 2
# Run as: sudo bash 02_postgresql_conf_changes.sh
# Server: ec2-user@13.203.181.76 (Server 2)
# PostgreSQL data dir: /var/lib/pgsql/17/data/
# ==============================================================================

set -euo pipefail

PG_CONF="/var/lib/pgsql/17/data/postgresql.conf"
LOG_PREFIX="[PG CONF $(date '+%Y-%m-%d %H:%M:%S')]"

echo "${LOG_PREFIX} Starting postgresql.conf hardening..."

# --- 1. Ensure we are running as root ----------------------------------------
if [[ "${EUID}" -ne 0 ]]; then
  echo "${LOG_PREFIX} ERROR: This script must be run as root (sudo)." >&2
  exit 1
fi

# --- 2. Ensure postgresql.conf exists ----------------------------------------
if [[ ! -f "${PG_CONF}" ]]; then
  echo "${LOG_PREFIX} ERROR: postgresql.conf not found at: ${PG_CONF}" >&2
  exit 1
fi

# --- 3. Create a dated backup of the original --------------------------------
BACKUP_FILE="${PG_CONF}.bak.$(date +%Y%m%d)"
cp "${PG_CONF}" "${BACKUP_FILE}"
echo "${LOG_PREFIX} Backup created: ${BACKUP_FILE}"

# --- Helper function: set or replace a postgresql.conf parameter -------------
# Usage: set_pg_param KEY VALUE
# - If the key exists (commented or not), replaces it.
# - If the key does not exist at all, appends it.
set_pg_param() {
  local KEY="$1"
  local VALUE="$2"

  if grep -qE "^#?\s*${KEY}\s*=" "${PG_CONF}"; then
    # Replace existing line (handles commented-out lines too)
    sed -i "s|^#\?\s*${KEY}\s*=.*|${KEY} = ${VALUE}|" "${PG_CONF}"
    echo "${LOG_PREFIX}   SET: ${KEY} = ${VALUE}"
  else
    # Append parameter at the end of the file
    echo "${KEY} = ${VALUE}" >> "${PG_CONF}"
    echo "${LOG_PREFIX}   APPENDED: ${KEY} = ${VALUE}"
  fi
}

# --- 4. Apply hardened settings ----------------------------------------------

echo "${LOG_PREFIX} Applying connection settings..."

# Restrict listen_addresses: only loopback and WireGuard VPN interface.
# Was: listen_addresses = '*' (ALL interfaces — insecure)
# Now: only 127.0.0.1 (local) and 10.100.0.1 (WireGuard hub IP on Server 2)
set_pg_param "listen_addresses" "'127.0.0.1,10.100.0.1'"

# Maximum simultaneous connections.
# 200 is appropriate for a single-node prod DB serving ~3 services.
# Increase to 300+ if connection pooling (PgBouncer) is added later (T-056).
set_pg_param "max_connections" "200"

echo "${LOG_PREFIX} Applying SSL settings..."

# Enable SSL — cert/key generated by 01_enable_ssl.sh
set_pg_param "ssl" "on"

echo "${LOG_PREFIX} Applying performance settings..."

# Shared memory for PostgreSQL buffer cache.
# 512MB is conservative for a server with ≥4GB RAM.
# Tune to ~25% of total RAM for a dedicated DB server.
set_pg_param "shared_buffers" "512MB"

echo "${LOG_PREFIX} Applying audit/logging settings..."

# Log every new connection (client IP, user, database) — required for SOC2 (T-046)
set_pg_param "log_connections" "on"

# Log every disconnection with session duration — pairs with log_connections
set_pg_param "log_disconnections" "on"

# Log queries that run longer than 1000ms (1 second) — identify slow queries
set_pg_param "log_min_duration_statement" "1000"

# Log all DDL statements (CREATE, ALTER, DROP, TRUNCATE) — required for SOC2 (T-046)
set_pg_param "log_statement" "'ddl'"

# --- 5. Show a diff so the operator can review changes -----------------------
echo ""
echo "=== Changes made to postgresql.conf ==="
diff "${BACKUP_FILE}" "${PG_CONF}" || true
echo "======================================="
echo ""

echo "${LOG_PREFIX} postgresql.conf hardening complete."
echo ""
echo "NEXT STEPS:"
echo "  1. Apply pg_hba.conf:  sudo cp pg_hba.conf /var/lib/pgsql/17/data/pg_hba.conf"
echo "                         sudo chown postgres:postgres /var/lib/pgsql/17/data/pg_hba.conf"
echo "  2. Restart PostgreSQL: sudo systemctl restart postgresql-17"
echo "  3. Verify:             sudo systemctl status postgresql-17"
echo "                         sudo -u postgres psql -c 'SHOW listen_addresses;'"
echo "                         sudo -u postgres psql -c 'SHOW ssl;'"
