#!/usr/bin/env bash
# ==============================================================================
# bootstrap-new-server.sh — ThinkVelocity Production Server Bootstrap
# Target : thinkvelocity-prod-v2 (8GB Lightsail, Ubuntu 24.04 LTS)
#
# Run as root on a FRESH Ubuntu 24.04 server:
#   sudo bash bootstrap-new-server.sh 2>&1 | tee /root/bootstrap.log
#
# What this does (11 steps):
#   1. SSH hardening
#   2. fail2ban
#   3. unattended-upgrades (security only)
#   4. Docker + Docker Compose plugin (official apt repo)
#   5. Nginx
#   6. Certbot (python3-certbot-nginx)
#   7. tv-net Docker network + PostgreSQL 17 via Docker (pgvector/pgvector:pg17)
#   8. Redis 7 via Docker
#   9. AWS CLI v2
#  10. Create directories
#  11. Install crons
#
# After this script completes:
#   - Deploy: scp configs/ to /opt/deploy/thinkvelocity/configs/
#   - Populate env files in /opt/deploy/*.env
#   - docker compose -f /opt/deploy/thinkvelocity/configs/prod/docker-compose-new-server.yml up -d
#   - certbot --nginx -d thinkvelocity.in -d www.thinkvelocity.in \
#             -d api.thinkvelocity.in -d enterprise.thinkvelocity.in \
#             -d grafana.thinkvelocity.in
#
# SOC2: CC6.1 (fail2ban), CC6.6 (SSH hardening), A1.2 (unattended-upgrades)
# ==============================================================================

set -euo pipefail

TOTAL_STEPS=11

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------
step() {
    echo ""
    echo "════════════════════════════════════════════════════════════"
    echo "[STEP $1/$TOTAL_STEPS] $2"
    echo "════════════════════════════════════════════════════════════"
}

ok() {
    echo "[OK] $1"
}

fail() {
    echo "[FAIL] $1" >&2
    exit 1
}

run() {
    "$@" || fail "Command failed: $*"
}

# Require root
if [[ "$(id -u)" -ne 0 ]]; then
    fail "This script must be run as root (use sudo)."
fi

# Update package index once upfront — all apt calls below use cached lists
export DEBIAN_FRONTEND=noninteractive
echo "Updating package lists..."
apt-get update -qq || fail "apt-get update failed"
ok "Package lists updated"

# ==============================================================================
# STEP 1/11 — SSH hardening
# ==============================================================================
step 1 "SSH hardening"

SSHD_CONFIG="/etc/ssh/sshd_config"

# Back up original
cp "$SSHD_CONFIG" "${SSHD_CONFIG}.bak.$(date +%Y%m%d%H%M%S)"

# Apply hardening — idempotent sed replacements + append if missing
apply_sshd_setting() {
    local key="$1"
    local value="$2"
    if grep -qE "^\s*#?\s*${key}\s" "$SSHD_CONFIG"; then
        sed -i "s|^\s*#\?\s*${key}\s.*|${key} ${value}|" "$SSHD_CONFIG"
    else
        echo "${key} ${value}" >> "$SSHD_CONFIG"
    fi
}

apply_sshd_setting "PasswordAuthentication" "no"
apply_sshd_setting "PermitRootLogin" "no"
apply_sshd_setting "MaxAuthTries" "3"
apply_sshd_setting "PubkeyAuthentication" "yes"
apply_sshd_setting "AuthorizedKeysFile" ".ssh/authorized_keys"
apply_sshd_setting "X11Forwarding" "no"
apply_sshd_setting "AllowTcpForwarding" "no"
apply_sshd_setting "ClientAliveInterval" "300"
apply_sshd_setting "ClientAliveCountMax" "2"

# Validate before restarting
sshd -t || fail "sshd config validation failed — check $SSHD_CONFIG"
# Ubuntu 24.04 uses 'ssh' service name (not 'sshd')
systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null || fail "sshd restart failed"
ok "SSH hardened: PasswordAuthentication=no, PermitRootLogin=no, MaxAuthTries=3"

# ==============================================================================
# STEP 2/11 — fail2ban
# ==============================================================================
step 2 "fail2ban"

run apt-get install -y -qq fail2ban

cat > /etc/fail2ban/jail.local <<'EOF'
# =============================================================================
# /etc/fail2ban/jail.local — ThinkVelocity Production
# Generated by bootstrap-new-server.sh
# =============================================================================

[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 5
backend  = auto

# ---------------------------------------------------------------------------
# SSH
# ---------------------------------------------------------------------------
[sshd]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 3

# ---------------------------------------------------------------------------
# Nginx — auth failures (401 / 403)
# ---------------------------------------------------------------------------
[nginx-auth]
enabled  = true
port     = http,https
filter   = nginx-http-auth
logpath  = /var/log/nginx/*error.log
maxretry = 5

# ---------------------------------------------------------------------------
# Nginx — bad bots (scanner / exploit probes)
# ---------------------------------------------------------------------------
[nginx-badbots]
enabled  = true
port     = http,https
filter   = nginx-badbots
logpath  = /var/log/nginx/*access.log
maxretry = 2

# ---------------------------------------------------------------------------
# Nginx — no-script (probing for .php/.asp/.cgi paths)
# ---------------------------------------------------------------------------
[nginx-noscript]
enabled  = true
port     = http,https
filter   = nginx-noscript
logpath  = /var/log/nginx/*access.log
maxretry = 6

# ---------------------------------------------------------------------------
# Nginx — overflow / large request attacks
# ---------------------------------------------------------------------------
[nginx-overflows]
enabled  = true
port     = http,https
filter   = nginx-limit-req
logpath  = /var/log/nginx/*error.log
maxretry = 10
EOF

systemctl enable --now fail2ban || fail "fail2ban enable/start failed"
ok "fail2ban installed, enabled, jails: sshd, nginx-auth, nginx-badbots, nginx-noscript, nginx-overflows"

# ==============================================================================
# STEP 3/11 — unattended-upgrades (security patches only)
# ==============================================================================
step 3 "unattended-upgrades (security patches only)"

run apt-get install -y -qq unattended-upgrades apt-listchanges

# Configure: security-only, no auto-reboot
cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
// /etc/apt/apt.conf.d/50unattended-upgrades
// ThinkVelocity Production — security patches only, no auto-reboot
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Package-Blacklist {
    // Do not auto-upgrade docker — controlled upgrade process
    "docker-ce";
    "docker-ce-cli";
    "containerd.io";
};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
Unattended-Upgrade::Remove-Unused-Dependencies "false";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Mail "";
Unattended-Upgrade::MailOnlyOnError "true";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOF

systemctl enable unattended-upgrades || fail "Failed to enable unattended-upgrades"
ok "unattended-upgrades configured: security-only, auto-reboot=false"

# ==============================================================================
# STEP 4/11 — Docker + Docker Compose plugin (official apt repo)
# ==============================================================================
step 4 "Docker + Docker Compose plugin (official apt repo, not snap)"

# Remove any snap/system Docker if present
apt-get remove -y -qq docker docker-engine docker.io containerd runc 2>/dev/null || true

# Prerequisites
run apt-get install -y -qq ca-certificates curl gnupg lsb-release

# Docker's official GPG key
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    || fail "Failed to download Docker GPG key"
chmod a+r /etc/apt/keyrings/docker.gpg

# Add Docker apt repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
  https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" \
  > /etc/apt/sources.list.d/docker.list

apt-get update -qq || fail "apt-get update after adding Docker repo failed"
run apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

systemctl enable --now docker || fail "Docker enable/start failed"

# Add ubuntu user to docker group
usermod -aG docker ubuntu || true

# Verify
COMPOSE_VERSION=$(docker compose version 2>&1) || fail "docker compose not available"
ok "Docker installed: $(docker --version)"
ok "Docker Compose plugin: $COMPOSE_VERSION"

# ==============================================================================
# STEP 5/11 — Nginx
# ==============================================================================
step 5 "Nginx"

run apt-get install -y -qq nginx
systemctl enable nginx || fail "nginx enable failed"

# Start only if not already running (certbot needs it)
systemctl is-active --quiet nginx || systemctl start nginx || fail "nginx start failed"

ok "Nginx installed and enabled: $(nginx -v 2>&1)"

# ==============================================================================
# STEP 6/11 — Certbot (python3-certbot-nginx, not snap)
# ==============================================================================
step 6 "Certbot (python3-certbot-nginx)"

run apt-get install -y -qq certbot python3-certbot-nginx

ok "Certbot installed: $(certbot --version 2>&1)"
echo "  NOTE: Run certbot after DNS is pointed at this server's Elastic IP:"
echo "    certbot --nginx -d thinkvelocity.in -d www.thinkvelocity.in \\"
echo "            -d api.thinkvelocity.in -d enterprise.thinkvelocity.in \\"
echo "            -d grafana.thinkvelocity.in"

# ==============================================================================
# STEP 7/11 — PostgreSQL 17 via Docker (pgvector/pgvector:pg17)
# ==============================================================================
step 7 "PostgreSQL 17 via Docker (pgvector/pgvector:pg17)"

# Create the shared external network FIRST. docker-compose-new-server.yml
# declares tv-net as `external: true` and pins all 4 app services to it —
# compose will refuse to start (or, pre-hardening, could silently fall back
# to an auto-created project-default network) if tv-net does not already
# exist. postgres17 and redis7 are standalone containers (not in compose) and
# must be attached to this same network so app containers can reach them by
# hostname (postgres17 / redis7) instead of host.docker.internal.
docker network create tv-net 2>/dev/null || true
ok "tv-net network present (created if missing, idempotent)"

# Create named volume explicitly
docker volume create postgres-data 2>/dev/null || true

# Remove existing container if it exists (idempotent re-run)
docker rm -f postgres17 2>/dev/null || true

docker run -d \
    --name postgres17 \
    --network tv-net \
    -e POSTGRES_PASSWORD=REPLACE_WITH_SM_KEY_PG_PASSWORD \
    -p 127.0.0.1:5432:5432 \
    -v postgres-data:/var/lib/postgresql/data \
    --restart unless-stopped \
    pgvector/pgvector:pg17 \
    || fail "Failed to start postgres17 container"

ok "postgres17 container started, waiting for healthy state..."

# Wait up to 60s for PostgreSQL to accept connections
RETRIES=12
until docker exec postgres17 pg_isready -U postgres -q 2>/dev/null; do
    RETRIES=$((RETRIES - 1))
    if [[ $RETRIES -le 0 ]]; then
        fail "PostgreSQL did not become ready within 60 seconds"
    fi
    echo "  ... waiting for PostgreSQL ($RETRIES retries left)"
    sleep 5
done

ok "PostgreSQL is accepting connections"

# Create application databases
docker exec -i postgres17 psql -U postgres <<'EOSQL'
-- Create databases (idempotent)
SELECT 'CREATE DATABASE thinkvelocity_prod'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'thinkvelocity_prod') \gexec

SELECT 'CREATE DATABASE enterprise'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'enterprise') \gexec

-- Confirm
\l
EOSQL
ok "Databases created: thinkvelocity_prod, enterprise"

# ==============================================================================
# STEP 8/11 — Redis 7 via Docker
# ==============================================================================
step 8 "Redis 7 via Docker (redis:7-alpine)"

# Remove existing container if it exists (idempotent re-run)
docker rm -f redis7 2>/dev/null || true

docker run -d \
    --name redis7 \
    --network tv-net \
    -p 127.0.0.1:6379:6379 \
    --restart unless-stopped \
    redis:7-alpine \
    redis-server --requirepass REPLACE_WITH_SM_KEY_REDIS_PASSWORD \
    || fail "Failed to start redis7 container"

ok "redis7 container started"

# Verify Redis is up (ping without auth fails — use auth ping)
sleep 2
docker exec redis7 redis-cli -a REPLACE_WITH_SM_KEY_REDIS_PASSWORD ping 2>/dev/null \
    | grep -q "PONG" || fail "Redis did not respond to PING — check container logs: docker logs redis7"
ok "Redis responding to PING"

# ==============================================================================
# STEP 9/11 — AWS CLI v2
# ==============================================================================
step 9 "AWS CLI v2 (official installer)"

# Download + install
run apt-get install -y -qq unzip

TMP_DIR=$(mktemp -d)
curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    -o "${TMP_DIR}/awscliv2.zip" \
    || fail "Failed to download AWS CLI v2"

unzip -q "${TMP_DIR}/awscliv2.zip" -d "${TMP_DIR}" || fail "Failed to unzip AWS CLI"
"${TMP_DIR}/aws/install" --update || fail "AWS CLI install script failed"
rm -rf "${TMP_DIR}"

AWS_VERSION=$(aws --version 2>&1) || fail "aws --version failed after install"
ok "AWS CLI installed: $AWS_VERSION"

# ==============================================================================
# STEP 10/11 — Create directories
# ==============================================================================
step 10 "Create application directories"

# Application directories
for dir in /opt/deploy /opt/backup /opt/observability; do
    mkdir -p "$dir"
    chown ubuntu:ubuntu "$dir"
    chmod 750 "$dir"
done

# Web roots
for dir in /var/www/velocity /var/www/enterprise; do
    mkdir -p "$dir"
    chown ubuntu:ubuntu "$dir"
    chmod 750 "$dir"
done

# Maintenance scripts dir (referenced by cron)
mkdir -p /opt/maintenance
chown ubuntu:ubuntu /opt/maintenance
chmod 750 /opt/maintenance

# Certbot webroot for ACME challenges
mkdir -p /var/www/certbot
chown www-data:www-data /var/www/certbot

ok "Directories created:"
ok "  /opt/deploy/         (deploy artifacts, env files)"
ok "  /opt/backup/         (backup scripts)"
ok "  /opt/observability/  (Prometheus, Loki, Grafana compose)"
ok "  /opt/maintenance/    (docker-cleanup.sh)"
ok "  /var/www/velocity/   (consumer Next.js static export)"
ok "  /var/www/enterprise/ (enterprise React build)"
ok "  /var/www/certbot/    (Let's Encrypt ACME challenges)"

# ==============================================================================
# STEP 11/11 — Install crons
# ==============================================================================
step 11 "Install cron jobs"

# Ensure cron is installed
run apt-get install -y -qq cron
systemctl enable --now cron || fail "cron enable/start failed"

# Install crontab for ubuntu user
# Note: IST = UTC+5:30, so 2am IST = 20:30 UTC previous day
CRONTAB_CONTENT=$(crontab -u ubuntu -l 2>/dev/null || echo "")

install_cron() {
    local schedule="$1"
    local command="$2"
    local comment="$3"

    if echo "$CRONTAB_CONTENT" | grep -qF "$command"; then
        echo "  [SKIP] Cron already present: $command"
    else
        CRONTAB_CONTENT="${CRONTAB_CONTENT}
# ${comment}
${schedule} ${command}"
        echo "  [ADD]  $schedule $command"
    fi
}

install_cron \
    "30 20 * * *" \
    "/opt/backup/pg-backup.sh >> /var/log/pg-backup.log 2>&1" \
    "pg-backup: daily at 2am IST (20:30 UTC)"

install_cron \
    "0 4 * * 0" \
    "/opt/maintenance/docker-cleanup.sh >> /var/log/docker-cleanup.log 2>&1" \
    "docker-cleanup: Sunday 4am UTC"

# Write back
echo "$CRONTAB_CONTENT" | crontab -u ubuntu - || fail "Failed to install crontab for ubuntu"

ok "Cron jobs installed for ubuntu user:"
ok "  20:30 UTC daily  → /opt/backup/pg-backup.sh (2am IST)"
ok "  04:00 UTC Sunday → /opt/maintenance/docker-cleanup.sh"

# Create placeholder log files with correct permissions
touch /var/log/pg-backup.log /var/log/docker-cleanup.log
chown ubuntu:ubuntu /var/log/pg-backup.log /var/log/docker-cleanup.log

# ==============================================================================
# DONE
# ==============================================================================
echo ""
echo "════════════════════════════════════════════════════════════"
echo " BOOTSTRAP COMPLETE — thinkvelocity-prod-v2"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Services running:"
echo "  docker ps -a"
docker ps -a --format "  {{.Names}}\t{{.Status}}\t{{.Ports}}"

echo ""
echo "Next steps:"
echo "  1. Point DNS to this server's Elastic IP"
echo "  2. Copy configs:  scp -r configs/ ubuntu@<IP>:/opt/deploy/thinkvelocity/configs/"
echo "  3. Populate env files in /opt/deploy/*.env  (pull from AWS Secrets Manager)"
echo "  4. Run certbot:   certbot --nginx -d thinkvelocity.in ..."
echo "  5. Start compose: docker compose -f /opt/deploy/thinkvelocity/configs/prod/docker-compose-new-server.yml up -d"
echo "  6. Copy backup script: cp configs/backup/pg-backup.sh /opt/backup/"
echo "  7. Copy cleanup script: cp configs/maintenance/docker-cleanup.sh /opt/maintenance/"
echo ""
echo "  IMPORTANT: Replace REPLACE_WITH_SM_KEY_PG_PASSWORD and"
echo "             REPLACE_WITH_SM_KEY_REDIS_PASSWORD in your deployment."
echo "             Recreate postgres17/redis7 containers with real passwords."
echo ""
echo "[OK] Bootstrap finished at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
